return {
  -- File operations
  { keys = ":e {file}", name = "Edit / open file", name_zh = "開啟檔案", tags = { "edit", "open", "file", "開啟", "檔案", "打開" }, category = "files", mnemonic = "e=edit", description = "Open a file for editing. Use :e to reload current file.", related = { ":find", ":new", "gf" } },
  { keys = ":e!", name = "Reload file (discard changes)", name_zh = "重新載入檔案（捨棄變更）", tags = { "reload", "discard", "revert", "file", "重新載入", "檔案", "捨棄" }, category = "files", mnemonic = "e! = edit force (discard)", description = "Reload current file from disk, discarding all unsaved changes", related = { ":e", "u" } },
  { keys = ":w", name = "Save file", name_zh = "儲存檔案", tags = { "write", "save", "file", "儲存", "存檔", "檔案" }, category = "files", mnemonic = "w=write", description = "Save the current file", related = { ":wq", ":wa", ":saveas" } },
  { keys = ":w {file}", name = "Save as", name_zh = "另存新檔", tags = { "write", "save", "file", "as", "另存", "新檔" }, category = "files", mnemonic = "w=write to file", description = "Save current buffer to a new file", related = { ":saveas", ":w" } },
  { keys = ":wa", name = "Save all files", name_zh = "儲存所有檔案", tags = { "write", "save", "all", "files", "儲存", "所有", "檔案" }, category = "files", mnemonic = "wa=write all", description = "Save all modified buffers", related = { ":w", ":wq" } },
  { keys = ":q", name = "Quit", name_zh = "關閉視窗", tags = { "quit", "close", "exit", "關閉", "離開", "退出" }, category = "files", mnemonic = "q=quit", description = "Close the current window. Fails if unsaved changes exist.", related = { ":q!", ":wq", ":qa" } },
  { keys = ":q!", name = "Force quit", name_zh = "強制關閉（不儲存）", tags = { "quit", "force", "close", "discard", "關閉", "強制", "不存" }, category = "files", mnemonic = "q! = quit force", description = "Close without saving. Discards unsaved changes.", related = { ":q", ":qa!" } },
  { keys = ":wq", name = "Save and quit", name_zh = "儲存並關閉", tags = { "write", "quit", "save", "close", "儲存", "關閉" }, category = "files", mnemonic = "wq=write quit", description = "Save the file and close the window", related = { "ZZ", ":x" } },
  { keys = "ZZ", name = "Save and quit (shortcut)", name_zh = "儲存並關閉（快捷鍵）", tags = { "save", "quit", "close", "shortcut", "儲存", "關閉" }, category = "files", mnemonic = "ZZ = quick save & quit", description = "Save file and quit (same as :wq)", related = { ":wq", "ZQ" } },
  { keys = "ZQ", name = "Quit without saving", name_zh = "不儲存直接關閉", tags = { "quit", "close", "discard", "不存", "關閉" }, category = "files", mnemonic = "ZQ = quick quit no save", description = "Quit without saving (same as :q!)", related = { ":q!", "ZZ" } },
  { keys = ":qa", name = "Quit all", name_zh = "關閉所有視窗", tags = { "quit", "all", "close", "exit", "關閉", "所有" }, category = "files", mnemonic = "qa=quit all", description = "Close all windows and exit Neovim", related = { ":qa!", ":wqa" } },
  { keys = ":saveas {file}", name = "Save as new name", name_zh = "另存為新檔名", tags = { "save", "as", "rename", "另存", "新檔", "更名" }, category = "files", mnemonic = "saveas = save as", description = "Save current file with a new name and switch to it", related = { ":w", ":file" } },

  -- File navigation
  { keys = ":find {file}", name = "Find and open file", name_zh = "在路徑中找並開啟檔案", tags = { "find", "open", "file", "path", "找", "開啟", "檔案", "路徑" }, category = "files", mnemonic = "find = find in path", description = "Search for {file} in 'path' and open it", related = { ":e", "gf" } },
  { keys = "gf", name = "Go to file under cursor", name_zh = "跳到游標下的檔案", tags = { "goto", "file", "cursor", "open", "跳", "檔案", "游標", "開啟" }, category = "files", mnemonic = "gf=go file", description = "Open the file whose name is under the cursor", related = { "gF", ":find", ":e" } },
  { keys = "gF", name = "Go to file:line under cursor", name_zh = "跳到游標下的檔案及行號", tags = { "goto", "file", "line", "cursor", "跳", "檔案", "行號" }, category = "files", mnemonic = "gF=go File with line", description = "Open file under cursor and jump to the line number after it", related = { "gf" } },
  { keys = ":Explore", name = "Open file explorer", name_zh = "開啟檔案瀏覽器", tags = { "explore", "browser", "directory", "netrw", "瀏覽", "檔案", "目錄" }, category = "files", mnemonic = "Explore = file explorer", description = "Open the built-in file explorer (netrw) in current window. Requires netrw (disabled in some distros like LazyVim).", related = { ":Sexplore", ":Vexplore", ":Lexplore" } },
  { keys = ":Sexplore", name = "File explorer (split)", name_zh = "水平分割開啟檔案瀏覽器", tags = { "explore", "split", "horizontal", "瀏覽", "分割" }, category = "files", mnemonic = "S=split explore", description = "Open file explorer in a horizontal split. Requires netrw.", related = { ":Explore", ":Vexplore" } },
  { keys = ":Vexplore", name = "File explorer (vsplit)", name_zh = "垂直分割開啟檔案瀏覽器", tags = { "explore", "split", "vertical", "瀏覽", "垂直" }, category = "files", mnemonic = "V=vertical explore", description = "Open file explorer in a vertical split. Requires netrw.", related = { ":Explore", ":Sexplore" } },

  -- Buffer management
  { keys = ":ls", name = "List buffers", name_zh = "列出所有 buffer", tags = { "buffer", "list", "列出", "緩衝區" }, category = "files.buffers", mnemonic = "ls = list", description = "List all open buffers", related = { ":bn", ":bp", ":b" } },
  { keys = ":bn", name = "Next buffer", name_zh = "下一個 buffer", tags = { "buffer", "next", "下一個", "緩衝區" }, category = "files.buffers", mnemonic = "bn=buffer next", description = "Switch to the next buffer", related = { ":bp", ":ls", ":b" } },
  { keys = ":bp", name = "Previous buffer", name_zh = "上一個 buffer", tags = { "buffer", "previous", "上一個", "緩衝區" }, category = "files.buffers", mnemonic = "bp=buffer previous", description = "Switch to the previous buffer", related = { ":bn", ":ls" } },
  { keys = ":b {name/num}", name = "Go to buffer", name_zh = "跳到指定 buffer", tags = { "buffer", "switch", "goto", "跳", "切換", "緩衝區" }, category = "files.buffers", mnemonic = "b=buffer", description = "Switch to buffer by name or number", related = { ":ls", ":bn", ":bp" } },
  { keys = ":bd", name = "Delete buffer", name_zh = "刪除 buffer", tags = { "buffer", "delete", "close", "刪除", "關閉", "緩衝區" }, category = "files.buffers", mnemonic = "bd=buffer delete", description = "Delete (close) the current buffer", related = { ":ls", ":bw" } },
  { keys = "Ctrl-^", name = "Alternate buffer", name_zh = "切換到上一個編輯的 buffer", tags = { "buffer", "alternate", "switch", "previous", "切換", "上一個", "緩衝區" }, category = "files.buffers", mnemonic = "Ctrl-^ = toggle last buffer", description = "Switch to the previously edited buffer", related = { ":b#", ":ls" } },

  -- Directory / path
  { keys = ":cd {dir}", name = "Change directory", name_zh = "切換工作目錄", tags = { "directory", "change", "cd", "path", "folder", "目錄", "切換", "資料夾" }, category = "files.directory", mnemonic = "cd=change directory", description = "Change Neovim's working directory", related = { ":lcd", ":pwd" } },
  { keys = ":lcd {dir}", name = "Change local directory", name_zh = "切換視窗本地目錄", tags = { "directory", "change", "local", "window", "目錄", "本地", "視窗" }, category = "files.directory", mnemonic = "lcd=local cd", description = "Change working directory for the current window only", related = { ":cd", ":pwd" } },
  { keys = ":pwd", name = "Print working directory", name_zh = "顯示目前工作目錄", tags = { "directory", "print", "current", "path", "pwd", "目錄", "顯示", "路徑" }, category = "files.directory", mnemonic = "pwd=print working dir", description = "Show the current working directory", related = { ":cd", ":lcd" } },

  -- Window splits
  { keys = ":sp {file}", name = "Horizontal split", name_zh = "水平分割視窗", tags = { "split", "horizontal", "window", "分割", "水平", "視窗" }, category = "files.windows", mnemonic = "sp=split", description = "Split window horizontally (optionally open file)", related = { ":vsp", "Ctrl-w s" } },
  { keys = ":vsp {file}", name = "Vertical split", name_zh = "垂直分割視窗", tags = { "split", "vertical", "window", "分割", "垂直", "視窗" }, category = "files.windows", mnemonic = "vsp=vertical split", description = "Split window vertically (optionally open file)", related = { ":sp", "Ctrl-w v" } },
  { keys = "Ctrl-w s", name = "Split horizontal", name_zh = "水平分割", tags = { "split", "horizontal", "window", "分割", "水平" }, category = "files.windows", mnemonic = "Ctrl-w s = split", description = "Split current window horizontally", related = { "Ctrl-w v", ":sp" } },
  { keys = "Ctrl-w v", name = "Split vertical", name_zh = "垂直分割", tags = { "split", "vertical", "window", "分割", "垂直" }, category = "files.windows", mnemonic = "Ctrl-w v = vertical", description = "Split current window vertically", related = { "Ctrl-w s", ":vsp" } },
  { keys = "Ctrl-w w", name = "Next window", name_zh = "切換到下一個視窗", tags = { "window", "next", "switch", "cycle", "視窗", "下一個", "切換" }, category = "files.windows", mnemonic = "Ctrl-w w = cycle window", description = "Cycle to the next window", related = { "Ctrl-w h/j/k/l" } },
  { keys = "Ctrl-w h", name = "Go to left window", name_zh = "跳到左邊的視窗", tags = { "window", "left", "navigate", "視窗", "左" }, category = "files.windows", mnemonic = "Ctrl-w h = left window", description = "Move cursor to the window on the left", related = { "Ctrl-w l", "Ctrl-w j", "Ctrl-w k" } },
  { keys = "Ctrl-w j", name = "Go to below window", name_zh = "跳到下方的視窗", tags = { "window", "below", "down", "navigate", "視窗", "下" }, category = "files.windows", mnemonic = "Ctrl-w j = down window", description = "Move cursor to the window below", related = { "Ctrl-w k", "Ctrl-w h", "Ctrl-w l" } },
  { keys = "Ctrl-w k", name = "Go to above window", name_zh = "跳到上方的視窗", tags = { "window", "above", "up", "navigate", "視窗", "上" }, category = "files.windows", mnemonic = "Ctrl-w k = up window", description = "Move cursor to the window above", related = { "Ctrl-w j", "Ctrl-w h", "Ctrl-w l" } },
  { keys = "Ctrl-w l", name = "Go to right window", name_zh = "跳到右邊的視窗", tags = { "window", "right", "navigate", "視窗", "右" }, category = "files.windows", mnemonic = "Ctrl-w l = right window", description = "Move cursor to the window on the right", related = { "Ctrl-w h", "Ctrl-w j", "Ctrl-w k" } },
  { keys = "Ctrl-w q", name = "Close window", name_zh = "關閉視窗", tags = { "window", "close", "quit", "視窗", "關閉" }, category = "files.windows", mnemonic = "Ctrl-w q = quit window", description = "Close the current window", related = { ":q", "Ctrl-w o" } },
  { keys = "Ctrl-w o", name = "Close other windows", name_zh = "關閉其他所有視窗", tags = { "window", "close", "other", "only", "視窗", "關閉", "其他" }, category = "files.windows", mnemonic = "Ctrl-w o = only this window", description = "Close all windows except the current one", related = { "Ctrl-w q" } },
  { keys = "Ctrl-w =", name = "Equal window sizes", name_zh = "平均分配視窗大小", tags = { "window", "resize", "equal", "視窗", "大小", "平均" }, category = "files.windows", mnemonic = "Ctrl-w = = equalize", description = "Make all windows equal size", related = { "Ctrl-w +", "Ctrl-w -" } },

  -- Tabs
  { keys = ":tabnew {file}", name = "New tab", name_zh = "開新分頁", tags = { "tab", "new", "create", "分頁", "新", "建立" }, category = "files.tabs", mnemonic = "tabnew = new tab", description = "Open a new tab (optionally with a file)", related = { ":tabclose", "gt" } },
  { keys = ":tabclose", name = "Close tab", name_zh = "關閉分頁", tags = { "tab", "close", "分頁", "關閉" }, category = "files.tabs", mnemonic = "tabclose = close tab", description = "Close the current tab", related = { ":tabnew", ":tabonly" } },
  { keys = "gt", name = "Next tab", name_zh = "下一個分頁", tags = { "tab", "next", "分頁", "下一個" }, category = "files.tabs", mnemonic = "gt=go tab (next)", description = "Go to the next tab", related = { "gT", ":tabnew" } },
  { keys = "gT", name = "Previous tab", name_zh = "上一個分頁", tags = { "tab", "previous", "分頁", "上一個" }, category = "files.tabs", mnemonic = "gT=go Tab (previous)", description = "Go to the previous tab", related = { "gt" } },
  { keys = "{n}gt", name = "Go to tab n", name_zh = "跳到第 n 個分頁", tags = { "tab", "goto", "number", "分頁", "跳", "指定" }, category = "files.tabs", mnemonic = "2gt = go to tab 2", description = "Go to tab number {n}", related = { "gt", "gT" } },
  { keys = ":tabmove {n}", name = "Move tab to position", name_zh = "移動分頁到指定位置", tags = { "tab", "move", "reorder", "分頁", "移動", "排序" }, category = "files.tabs", mnemonic = "tabmove = move tab", description = "Move current tab to position {n} (0=first). Omit {n} to move to last.", related = { "gt", "gT" } },
  { keys = ":tabonly", name = "Close other tabs", name_zh = "關閉其他所有分頁", tags = { "tab", "close", "other", "only", "分頁", "關閉", "其他" }, category = "files.tabs", mnemonic = "tabonly = keep only this tab", description = "Close all other tabs, keep only the current one", related = { ":tabclose" } },
  { keys = "set tabline=...", name = "Rename / customize tab label", name_zh = "重新命名分頁標籤", tags = { "tab", "rename", "name", "label", "title", "分頁", "重新命名", "名稱", "標籤", "改名" }, category = "files.tabs", mnemonic = "No built-in rename; use tabline", description = "Neovim has no :tabrename. Tabs show the buffer filename. To customize: use 'tabline' option or a plugin like bufferline.nvim / tabby.nvim.", related = { ":tabnew", "gt" } },
}
