return {
  -- Line numbers
  { keys = "set number", name = "Show line numbers", name_zh = "顯示行號", tags = { "number", "line", "行號", "顯示", "設定" }, category = "settings.display", mnemonic = "number = line numbers", description = "Display line numbers in the gutter" },
  { keys = "set relativenumber", name = "Relative line numbers", name_zh = "顯示相對行號", tags = { "relative", "number", "line", "相對", "行號" }, category = "settings.display", mnemonic = "relativenumber = relative to cursor", description = "Show line numbers relative to cursor position. Combine with 'number' for hybrid mode." },
  { keys = "set numberwidth={n}", name = "Line number column width", name_zh = "行號欄寬度", tags = { "number", "width", "column", "行號", "寬度" }, category = "settings.display", mnemonic = "numberwidth = gutter width", description = "Set minimum width of the line number column (default: 4)" },

  -- Syntax & colors
  { keys = "syntax on", name = "Enable syntax highlighting", name_zh = "啟用語法高亮", tags = { "syntax", "highlight", "color", "語法", "高亮", "顏色" }, category = "settings.syntax", mnemonic = "syntax on = colorize code", description = "Enable syntax highlighting. In Neovim with Treesitter, this is often automatic." },
  { keys = "syntax off", name = "Disable syntax highlighting", name_zh = "關閉語法高亮", tags = { "syntax", "highlight", "off", "disable", "語法", "高亮", "關閉" }, category = "settings.syntax", mnemonic = "syntax off = no colors", description = "Disable syntax highlighting for the current buffer" },
  { keys = "set termguicolors", name = "True color support", name_zh = "啟用 24-bit 真彩色", tags = { "color", "true", "gui", "24bit", "terminal", "顏色", "真彩", "終端" }, category = "settings.syntax", mnemonic = "termguicolors = full color palette", description = "Enable 24-bit RGB color in the terminal. Required for most modern color schemes." },
  { keys = "colorscheme {name}", name = "Set color scheme", name_zh = "設定配色方案", tags = { "color", "scheme", "theme", "配色", "主題", "顏色" }, category = "settings.syntax", mnemonic = "colorscheme = pick a theme", description = "Change the color scheme (e.g. colorscheme catppuccin)" },
  { keys = "set background={dark|light}", name = "Set background mode", name_zh = "設定背景模式（深色/淺色）", tags = { "background", "dark", "light", "背景", "深色", "淺色" }, category = "settings.syntax", mnemonic = "background = dark or light", description = "Tell Neovim your terminal background is dark or light for better contrast" },
  { keys = "set cursorline", name = "Highlight current line", name_zh = "高亮當前行", tags = { "cursor", "line", "highlight", "current", "游標", "高亮", "當前行" }, category = "settings.syntax", mnemonic = "cursorline = highlight where I am", description = "Highlight the line the cursor is on" },
  { keys = "set cursorcolumn", name = "Highlight current column", name_zh = "高亮當前列", tags = { "cursor", "column", "highlight", "游標", "高亮", "列" }, category = "settings.syntax", mnemonic = "cursorcolumn = vertical highlight", description = "Highlight the column the cursor is on" },
  { keys = "set colorcolumn={n}", name = "Show column guide", name_zh = "顯示欄位參考線", tags = { "column", "guide", "ruler", "width", "欄位", "參考線" }, category = "settings.syntax", mnemonic = "colorcolumn = line length guide", description = "Display a colored column at position {n} (e.g. 80) as a line-length guide" },
  { keys = "set showmatch", name = "Highlight matching bracket", name_zh = "高亮匹配的括號", tags = { "match", "bracket", "highlight", "匹配", "括號", "高亮" }, category = "settings.syntax", mnemonic = "showmatch = flash matching paren", description = "Briefly highlight the matching bracket when one is typed" },

  -- Indentation & tabs
  { keys = "set tabstop={n}", name = "Tab display width", name_zh = "Tab 顯示寬度", tags = { "tab", "width", "size", "tabstop", "寬度", "縮排" }, category = "settings.indent", mnemonic = "tabstop = how wide tabs look", description = "Number of spaces a <Tab> character displays as (default: 8)" },
  { keys = "set shiftwidth={n}", name = "Indent width", name_zh = "縮排寬度", tags = { "indent", "width", "shift", "縮排", "寬度" }, category = "settings.indent", mnemonic = "shiftwidth = indent step size", description = "Number of spaces used for each step of (auto)indent and >> << commands" },
  { keys = "set softtabstop={n}", name = "Soft tab width", name_zh = "軟 Tab 寬度", tags = { "tab", "soft", "width", "Tab", "軟" }, category = "settings.indent", mnemonic = "softtabstop = tab key feel", description = "Number of spaces inserted when pressing <Tab> in insert mode" },
  { keys = "set expandtab", name = "Use spaces instead of tabs", name_zh = "用空格取代 Tab", tags = { "tab", "space", "expand", "空格", "Tab", "取代" }, category = "settings.indent", mnemonic = "expandtab = spaces not tabs", description = "Convert <Tab> to spaces. Most modern projects prefer spaces." },
  { keys = "set autoindent", name = "Auto indent new lines", name_zh = "新行自動縮排", tags = { "auto", "indent", "自動", "縮排" }, category = "settings.indent", mnemonic = "autoindent = keep indent level", description = "Copy indent from current line when starting a new line" },
  { keys = "set smartindent", name = "Smart auto indent", name_zh = "智慧自動縮排", tags = { "smart", "indent", "auto", "智慧", "縮排" }, category = "settings.indent", mnemonic = "smartindent = language-aware indent", description = "Smart autoindenting when starting a new line (recognizes { } etc.)" },
  { keys = "set list", name = "Show invisible characters", name_zh = "顯示不可見字元", tags = { "list", "invisible", "whitespace", "tab", "space", "不可見", "空白", "字元" }, category = "settings.indent", mnemonic = "list = show hidden chars", description = "Display tabs as >-, trailing spaces as ·, etc. Customize with 'listchars'." },
  { keys = "set listchars=...", name = "Configure invisible chars", name_zh = "設定不可見字元的顯示方式", tags = { "listchars", "invisible", "whitespace", "tab", "不可見", "空白" }, category = "settings.indent", mnemonic = "listchars = what hidden chars look like", description = "e.g. set listchars=tab:▸\\ ,trail:·,extends:›,precedes:‹,nbsp:+" },

  -- Search
  { keys = "set hlsearch", name = "Highlight search results", name_zh = "高亮搜尋結果", tags = { "highlight", "search", "高亮", "搜尋" }, category = "settings.search", mnemonic = "hlsearch = highlight matches", description = "Highlight all matches of the search pattern" },
  { keys = "set incsearch", name = "Incremental search", name_zh = "漸進式搜尋", tags = { "incremental", "search", "漸進", "搜尋" }, category = "settings.search", mnemonic = "incsearch = search as you type", description = "Show matches as you type the search pattern" },
  { keys = "set ignorecase", name = "Case insensitive search", name_zh = "搜尋不分大小寫", tags = { "case", "insensitive", "search", "ignore", "大小寫", "搜尋" }, category = "settings.search", mnemonic = "ignorecase = ignore CASE", description = "Ignore case in search patterns" },
  { keys = "set smartcase", name = "Smart case search", name_zh = "智慧大小寫搜尋", tags = { "smart", "case", "search", "智慧", "大小寫", "搜尋" }, category = "settings.search", mnemonic = "smartcase = case-sensitive if uppercase used", description = "Override ignorecase if search pattern contains uppercase letters" },

  -- UI elements
  { keys = "set signcolumn=yes", name = "Always show sign column", name_zh = "永遠顯示標記欄", tags = { "sign", "column", "gutter", "標記", "欄" }, category = "settings.ui", mnemonic = "signcolumn = left gutter for signs", description = "Always show the sign column (prevents text shifting when diagnostics appear)" },
  { keys = "set laststatus={n}", name = "Status line display", name_zh = "狀態列顯示方式", tags = { "status", "line", "bar", "狀態列" }, category = "settings.ui", mnemonic = "laststatus: 0=never, 2=always, 3=global", description = "0=never, 1=only if split, 2=always, 3=single global status line" },
  { keys = "set showcmd", name = "Show partial command", name_zh = "顯示輸入中的指令", tags = { "show", "command", "partial", "顯示", "指令" }, category = "settings.ui", mnemonic = "showcmd = show what I'm typing", description = "Show the (partial) command in the bottom right as you type it" },
  { keys = "set showmode", name = "Show current mode", name_zh = "顯示目前模式", tags = { "show", "mode", "insert", "normal", "顯示", "模式" }, category = "settings.ui", mnemonic = "showmode = show INSERT/NORMAL", description = "Show -- INSERT --, -- VISUAL -- etc. at the bottom" },
  { keys = "set ruler", name = "Show cursor position", name_zh = "顯示游標位置", tags = { "ruler", "position", "cursor", "row", "column", "游標", "位置" }, category = "settings.ui", mnemonic = "ruler = show line:col", description = "Show line number and column number in the status line" },
  { keys = "set scrolloff={n}", name = "Scroll offset", name_zh = "捲動時保留的行數", tags = { "scroll", "offset", "margin", "捲動", "邊距" }, category = "settings.ui", mnemonic = "scrolloff = keep N lines visible above/below", description = "Minimum number of lines to keep above and below the cursor when scrolling" },
  { keys = "set sidescrolloff={n}", name = "Horizontal scroll offset", name_zh = "水平捲動時保留的欄數", tags = { "scroll", "horizontal", "offset", "捲動", "水平" }, category = "settings.ui", mnemonic = "sidescrolloff = horizontal margin", description = "Minimum columns to keep left/right of cursor when scrolling horizontally" },
  { keys = "set wrap", name = "Wrap long lines", name_zh = "自動換行", tags = { "wrap", "line", "long", "換行", "自動" }, category = "settings.ui", mnemonic = "wrap = soft wrap long lines", description = "Visually wrap lines that exceed window width (does not insert newlines)" },
  { keys = "set nowrap", name = "Disable line wrap", name_zh = "關閉自動換行", tags = { "wrap", "disable", "nowrap", "換行", "關閉" }, category = "settings.ui", mnemonic = "nowrap = horizontal scroll instead", description = "Do not wrap long lines; scroll horizontally instead" },
  { keys = "set linebreak", name = "Wrap at word boundary", name_zh = "在字邊界換行", tags = { "wrap", "word", "linebreak", "換行", "字" }, category = "settings.ui", mnemonic = "linebreak = wrap at words not mid-char", description = "When wrapping, break at word boundaries instead of mid-word" },
  { keys = "set splitbelow", name = "Split below", name_zh = "水平分割時新視窗在下方", tags = { "split", "below", "window", "分割", "下方" }, category = "settings.ui", mnemonic = "splitbelow = new splits go down", description = "Horizontal splits open below the current window" },
  { keys = "set splitright", name = "Split right", name_zh = "垂直分割時新視窗在右方", tags = { "split", "right", "window", "分割", "右方" }, category = "settings.ui", mnemonic = "splitright = new splits go right", description = "Vertical splits open to the right of the current window" },

  -- Clipboard & mouse
  { keys = "set clipboard=unnamedplus", name = "Use system clipboard", name_zh = "使用系統剪貼簿", tags = { "clipboard", "system", "copy", "paste", "剪貼簿", "系統", "複製", "貼上" }, category = "settings.clipboard", mnemonic = "unnamedplus = sync with OS clipboard", description = "Yank and paste use the system clipboard. Requires clipboard provider." },
  { keys = "set mouse=a", name = "Enable mouse support", name_zh = "啟用滑鼠支援", tags = { "mouse", "click", "scroll", "滑鼠", "支援" }, category = "settings.clipboard", mnemonic = "mouse=a = mouse in all modes", description = "Enable mouse support in all modes (click, scroll, select)" },

  -- File handling
  { keys = "set autoread", name = "Auto reload changed files", name_zh = "自動重新載入外部修改的檔案", tags = { "auto", "read", "reload", "file", "change", "自動", "載入", "檔案" }, category = "settings.files", mnemonic = "autoread = detect external changes", description = "Automatically reload files when changed outside of Neovim" },
  { keys = "set hidden", name = "Allow hidden buffers", name_zh = "允許隱藏未儲存的 buffer", tags = { "hidden", "buffer", "unsaved", "隱藏", "緩衝區" }, category = "settings.files", mnemonic = "hidden = switch buffers without saving", description = "Allow switching buffers without saving. Neovim default is on." },
  { keys = "set noswapfile", name = "Disable swap files", name_zh = "關閉 swap 檔案", tags = { "swap", "file", "disable", "swap", "檔案", "關閉" }, category = "settings.files", mnemonic = "noswapfile = no .swp files", description = "Do not create swap files. Reduces clutter but loses crash recovery." },
  { keys = "set undofile", name = "Persistent undo", name_zh = "持久化撤銷歷史", tags = { "undo", "persistent", "file", "history", "撤銷", "持久", "歷史" }, category = "settings.files", mnemonic = "undofile = undo survives restart", description = "Save undo history to file so you can undo after closing and reopening" },
  { keys = "set encoding=utf-8", name = "Set encoding to UTF-8", name_zh = "設定編碼為 UTF-8", tags = { "encoding", "utf8", "unicode", "編碼" }, category = "settings.files", mnemonic = "encoding = character set", description = "Set internal encoding to UTF-8 (Neovim default)" },
  { keys = "set fileformats=unix,dos", name = "File format priority", name_zh = "檔案格式優先順序", tags = { "file", "format", "unix", "dos", "line ending", "檔案", "格式", "換行" }, category = "settings.files", mnemonic = "fileformats = line ending preference", description = "Prefer Unix line endings (LF), fall back to DOS (CRLF)" },

  -- Folding
  { keys = "set foldmethod={method}", name = "Set fold method", name_zh = "設定摺疊方式", tags = { "fold", "method", "摺疊", "方式" }, category = "settings.fold", mnemonic = "foldmethod: manual, indent, syntax, expr, marker", description = "How folds are created: manual, indent, syntax, expr, marker, diff" },
  { keys = "set foldlevel={n}", name = "Default fold level", name_zh = "預設摺疊層級", tags = { "fold", "level", "open", "摺疊", "層級" }, category = "settings.fold", mnemonic = "foldlevel = how many levels open by default", description = "Folds deeper than {n} are closed on file open. 99 = all open." },
  { keys = "za", name = "Toggle fold", name_zh = "切換摺疊", tags = { "fold", "toggle", "摺疊", "切換" }, category = "settings.fold", mnemonic = "za = alternate fold state", description = "Toggle fold under cursor: open if closed, close if open", related = { "zo", "zc", "zR", "zM" } },
  { keys = "zo", name = "Open fold", name_zh = "展開摺疊", tags = { "fold", "open", "摺疊", "展開" }, category = "settings.fold", mnemonic = "zo = open fold", description = "Open the fold under cursor", related = { "zc", "za", "zR" } },
  { keys = "zc", name = "Close fold", name_zh = "關閉摺疊", tags = { "fold", "close", "摺疊", "關閉" }, category = "settings.fold", mnemonic = "zc = close fold", description = "Close the fold under cursor", related = { "zo", "za", "zM" } },
  { keys = "zR", name = "Open all folds", name_zh = "展開所有摺疊", tags = { "fold", "open", "all", "摺疊", "全部", "展開" }, category = "settings.fold", mnemonic = "zR = Reduce all folds (open everything)", description = "Open every fold in the file", related = { "zM", "za" } },
  { keys = "zM", name = "Close all folds", name_zh = "關閉所有摺疊", tags = { "fold", "close", "all", "摺疊", "全部", "關閉" }, category = "settings.fold", mnemonic = "zM = More folds (close everything)", description = "Close every fold in the file", related = { "zR", "za" } },

  -- Completion & wildmenu
  { keys = "set wildmenu", name = "Enhanced command completion", name_zh = "增強指令列補全", tags = { "wild", "menu", "completion", "command", "補全", "指令" }, category = "settings.completion", mnemonic = "wildmenu = tab completion popup", description = "Show completion menu for command-line (e.g. :e <Tab>)" },
  { keys = "set wildmode=longest:full,full", name = "Wild completion mode", name_zh = "補全行為模式", tags = { "wild", "mode", "completion", "補全", "模式" }, category = "settings.completion", mnemonic = "wildmode = how completion behaves", description = "Complete longest common string first, then cycle through full matches" },
  { keys = "set completeopt=menu,menuone,noselect", name = "Completion options", name_zh = "自動補全選項", tags = { "complete", "option", "popup", "menu", "補全", "選項" }, category = "settings.completion", mnemonic = "completeopt = completion popup behavior", description = "Show menu even for one match, don't auto-select. Recommended for nvim-cmp." },
  { keys = "set pumheight={n}", name = "Popup menu height", name_zh = "補全彈出選單高度", tags = { "popup", "menu", "height", "completion", "彈出", "選單", "高度" }, category = "settings.completion", mnemonic = "pumheight = max popup rows", description = "Maximum number of items shown in the completion popup menu" },

  -- Misc
  { keys = "set timeoutlen={ms}", name = "Key sequence timeout", name_zh = "按鍵序列超時時間", tags = { "timeout", "key", "mapping", "sequence", "超時", "按鍵" }, category = "settings.misc", mnemonic = "timeoutlen = how long to wait for key combo", description = "Time in ms to wait for a mapped key sequence (default: 1000). Lower = snappier." },
  { keys = "set updatetime={ms}", name = "Update time", name_zh = "更新時間", tags = { "update", "time", "swap", "cursor", "更新", "時間" }, category = "settings.misc", mnemonic = "updatetime = idle trigger delay", description = "Time in ms before CursorHold triggers and swap file writes (default: 4000). 250 recommended." },
  { keys = "set conceallevel={n}", name = "Conceal level", name_zh = "隱藏層級", tags = { "conceal", "level", "markdown", "json", "隱藏" }, category = "settings.misc", mnemonic = "conceallevel: 0=show all, 2=hide completely", description = "How concealed text is shown: 0=visible, 1=replacement char, 2=hidden, 3=fully hidden" },
  { keys = "set spell", name = "Enable spell check", name_zh = "啟用拼字檢查", tags = { "spell", "check", "拼字", "檢查" }, category = "settings.misc", mnemonic = "spell = underline misspelled words", description = "Enable spell checking. Use ]s/[s to jump, z= for suggestions." },
  { keys = "set spelllang={lang}", name = "Spell check language", name_zh = "拼字檢查語言", tags = { "spell", "language", "拼字", "語言" }, category = "settings.misc", mnemonic = "spelllang = which language to check", description = "Set spell check language (e.g. en_us, en_gb)" },
}
